import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vineet Mehenwal
 */
public class Book_Return extends javax.swing.JFrame {

    /**
     * Creates new form Book_Return
     */
    public Book_Return() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar4 = new javax.swing.JToolBar();
        BtnHome3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        RBStud = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        RBTeach = new javax.swing.JRadioButton();
        TxtClass = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lcls = new javax.swing.JLabel();
        TxtFname = new javax.swing.JTextField();
        lsec = new javax.swing.JLabel();
        TxtSec = new javax.swing.JTextField();
        TxtLName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pimg = new javax.swing.JLabel();
        TxtAOT = new javax.swing.JTextField();
        LabelID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtAuthor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtISBN = new javax.swing.JTextField();
        TxtBID = new javax.swing.JTextField();
        TxtBName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtPub = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtCopies = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cimg = new javax.swing.JLabel();
        TxtBType = new javax.swing.JTextField();
        BtnBDGo = new javax.swing.JButton();
        BtnReturn = new javax.swing.JButton();
        TxtCurl = new javax.swing.JTextField();
        TxtPurl = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        IssueMBtnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar4.setRollover(true);

        BtnHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        BtnHome3.setFocusable(false);
        BtnHome3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnHome3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/homero.png"))); // NOI18N
        BtnHome3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHome3ActionPerformed(evt);
            }
        });
        jToolBar4.add(BtnHome3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/returnthumb.png"))); // NOI18N
        jLabel3.setText("Book Return Menu");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Issued By"));
        jPanel3.setEnabled(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("User Status"));

        RBStud.setEnabled(false);
        RBStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBStudActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/student.png"))); // NOI18N
        jLabel11.setText("Student");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teacher.png"))); // NOI18N
        jLabel12.setText("Teacher");

        RBTeach.setEnabled(false);
        RBTeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTeachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBStud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RBTeach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RBStud)
                    .addComponent(RBTeach)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        TxtClass.setEnabled(false);

        jLabel14.setText("First Name : ");

        lcls.setText("Class : ");

        TxtFname.setEnabled(false);
        TxtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFnameActionPerformed(evt);
            }
        });

        lsec.setText("Section : ");

        TxtSec.setEnabled(false);
        TxtSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSecActionPerformed(evt);
            }
        });

        TxtLName.setEnabled(false);

        jLabel17.setText("Last Name : ");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Photograph"));

        pimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pimg, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(pimg, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        TxtAOT.setEditable(false);
        TxtAOT.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtAOTCaretUpdate(evt);
            }
        });

        LabelID.setText("Admission No:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lcls)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TxtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lsec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtSec))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtAOT)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelID)
                    .addComponent(TxtAOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TxtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lcls)
                        .addComponent(lsec))
                    .addComponent(TxtSec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Book Details"));

        jLabel5.setText("Type:");

        jLabel1.setText("Enter Book ID:");

        jLabel6.setText("Author Name:");

        TxtAuthor.setEditable(false);
        TxtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAuthorActionPerformed(evt);
            }
        });

        jLabel4.setText("ISBN:");

        TxtISBN.setEditable(false);
        TxtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtISBNActionPerformed(evt);
            }
        });

        TxtBID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBIDActionPerformed(evt);
            }
        });

        TxtBName.setEditable(false);
        TxtBName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBNameActionPerformed(evt);
            }
        });

        jLabel7.setText("Book Name:");

        TxtPub.setEditable(false);
        TxtPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPubActionPerformed(evt);
            }
        });

        jLabel8.setText("Publisher:");

        TxtCopies.setEditable(false);
        TxtCopies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCopiesActionPerformed(evt);
            }
        });

        jLabel9.setText("Copies:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cover Photo"));

        cimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cimg, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cimg, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TxtBType.setEditable(false);
        TxtBType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBTypeActionPerformed(evt);
            }
        });

        BtnBDGo.setText("Go");
        BtnBDGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBDGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtBName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtPub, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtCopies, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TxtBID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBDGo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBDGo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(TxtBType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCopies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel1)
                    .addContainerGap(457, Short.MAX_VALUE)))
        );

        BtnReturn.setMnemonic('r');
        BtnReturn.setText("Return");
        BtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturnActionPerformed(evt);
            }
        });

        TxtCurl.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtCurlCaretUpdate(evt);
            }
        });

        TxtPurl.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtPurlCaretUpdate(evt);
            }
        });

        jMenu1.setText("File");

        IssueMBtnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        IssueMBtnExit.setText("Exit");
        IssueMBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueMBtnExitActionPerformed(evt);
            }
        });
        jMenu1.add(IssueMBtnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Status");

        jMenuItem1.setText("Total Books");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Currently Available");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Total Fine Earned");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TxtCurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BtnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TxtPurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(388, 388, 388))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnReturn)
                    .addComponent(TxtCurl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtPurl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IssueMBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueMBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_IssueMBtnExitActionPerformed

    private void BtnHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHome3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnHome3ActionPerformed

    private void RBStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBStudActionPerformed
        LabelID.setText("Enter Admission No:");
        lcls.setVisible(true);
        TxtClass.setVisible(true);
        lsec.setVisible(true);
        TxtSec.setVisible(true);
    }//GEN-LAST:event_RBStudActionPerformed

    private void RBTeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTeachActionPerformed
        LabelID.setText("Enter Teacher ID");
        lcls.setVisible(false);
        TxtClass.setVisible(false);
        lsec.setVisible(false);
        TxtSec.setVisible(false);
    }//GEN-LAST:event_RBTeachActionPerformed

    private void TxtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFnameActionPerformed

    private void TxtSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSecActionPerformed

   }//GEN-LAST:event_TxtSecActionPerformed

    private void TxtAOTCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtAOTCaretUpdate
        System.out.println("Hello");
        if (RBStud.isSelected() == true) {
            try {
                Class.forName("java.sql.Driver");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library", "root", "");
                Statement stmt = (Statement) con.createStatement();
                String q1 = "SELECT * FROM Student WHERE Admno='" + TxtAOT.getText() + "';";
                System.out.println(q1);
                ResultSet rs = stmt.executeQuery(q1);
                while (rs.next()) {
                    TxtFname.setText(rs.getString("First_Name"));
                    TxtLName.setText(rs.getString("Last_Name"));
                    TxtClass.setText(rs.getString("Class"));
                    TxtSec.setText(rs.getString("Section"));
                    TxtPurl.setText(rs.getString("PURL"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        if (RBTeach.isSelected() == true) {
            try {
                Class.forName("java.sql.Driver");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library", "root", "");
                Statement stmt = (Statement) con.createStatement();
                String q1 = "SELECT * FROM Teacher WHERE TID='" + TxtAOT.getText() + "';";
                System.out.println(q1);
                ResultSet rs = stmt.executeQuery(q1);
                while (rs.next()) {
                    TxtFname.setText(rs.getString("First_Name"));
                    TxtLName.setText(rs.getString("Last_Name"));
                    TxtPurl.setText(rs.getString("PURL"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_TxtAOTCaretUpdate

    private void TxtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAuthorActionPerformed

    private void TxtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtISBNActionPerformed

    private void TxtBIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBIDActionPerformed

    private void TxtBNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBNameActionPerformed

    private void TxtPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPubActionPerformed

    private void TxtCopiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCopiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCopiesActionPerformed

    private void TxtBTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBTypeActionPerformed

    private void BtnBDGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBDGoActionPerformed
        String uid = null, utype = null;
        if (TxtBID.getText().equals("") == false) {
            try {
                Class.forName("java.sql.Driver");
                com.mysql.jdbc.Connection con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library", "root", "");
                com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                String q1 = "SELECT * FROM Books WHERE Book_ID=" + TxtBID.getText() + ";";
                String q2 = "Select Designation,uid FROM ISSUE WHERE Book_ID=" + TxtBID.getText() + ";";
                System.out.println(q1);
                ResultSet rs = stmt.executeQuery(q1);
                while (rs.next()) {
                    TxtISBN.setText(rs.getString("ISBN"));
                    TxtBName.setText(rs.getString("Book_Name"));
                    TxtBType.setText(rs.getString("Book_Type"));
                    TxtAuthor.setText(rs.getString("Author"));
                    TxtPub.setText(rs.getString("Publisher"));
                    TxtCopies.setText(rs.getString("Copies_Available"));
                    TxtCurl.setText(rs.getString("CURL"));
                }System.out.println(q2);
                ResultSet rs2=stmt.executeQuery(q2);
                while (rs2.next()) {
                    uid = rs2.getString("uid");
                    utype=rs2.getString("Designation");                  
                }
                if (utype.equals("s")==true) {
                        LabelID.setText("Admission No:");
                        lcls.setVisible(true);
                        TxtClass.setVisible(true);
                        lsec.setVisible(true);
                        TxtSec.setVisible(true);
                        RBStud.setSelected(true);
                        TxtAOT.setText(uid);
                    } else if (utype.equals("t")==true) {
                        LabelID.setText("Teacher ID");
                        lcls.setVisible(false);
                        TxtClass.setVisible(false);
                        lsec.setVisible(false);
                        TxtSec.setVisible(false);
                        RBTeach.setSelected(true);
                        TxtAOT.setText(uid);
                    } else {
                        JOptionPane.showMessageDialog(this, "This Book is not Issued By Any Student or any Teacher");
                        this.setVisible(false);
                        new Home().setVisible(true);
                    }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Book ID !!!");
        }
    }//GEN-LAST:event_BtnBDGoActionPerformed

    private void BtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturnActionPerformed
        int Days = 0, fine = 0;
        if (TxtBID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid BookID First!!!");
        } else {
            try {
                Class.forName("java.sql.Driver");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library", "root", "");
                Statement stmt = (Statement) con.createStatement();
                String q1 = "SELECT CURDATE()-Issue_Date'day' FROM Issue WHERE Book_ID='" + TxtBID.getText() + "' ;";  
                System.out.println(q1);
                ResultSet rs = stmt.executeQuery(q1);
                while (rs.next()) {
                    Days = rs.getInt("day");
                }
                fine=Days*1-7;
                if(fine>0)
                    JOptionPane.showMessageDialog(this, "Total Fine to be paid is RS. "+fine);
                else
                    JOptionPane.showMessageDialog(this, "No Fine to be paid");
                String query = "DELETE FROM ISSUE WHERE Book_ID='" + TxtBID.getText() + "';";
                String upd = "UPDATE Books set Copies_Available=Copies_available+1 where Book_ID='" + TxtBID.getText() + "';";
                stmt.executeUpdate(query);
                stmt.executeUpdate(upd);
                JOptionPane.showMessageDialog(this, "Book Returned Successfully!!!");
                this.dispose();
                new Book_Return().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }

//GEN-LAST:event_BtnReturnActionPerformed

    private void TxtCurlCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtCurlCaretUpdate
        Image img = Toolkit.getDefaultToolkit().createImage("E:\\TEMP\\"+TxtCurl.getText()+".JPG").getScaledInstance(192, 235, 0);
        ImageIcon ic = new ImageIcon(img);
        cimg.setIcon(ic);
    }//GEN-LAST:event_TxtCurlCaretUpdate

    private void TxtPurlCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtPurlCaretUpdate
        Image img = Toolkit.getDefaultToolkit().createImage("E:\\TEMP\\"+TxtPurl.getText()+".JPG").getScaledInstance(192, 235, 0);
        ImageIcon ic = new ImageIcon(img);
        pimg.setIcon(ic);
    }//GEN-LAST:event_TxtPurlCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Book_Return().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBDGo;
    private javax.swing.JButton BtnHome3;
    private javax.swing.JButton BtnReturn;
    private javax.swing.JMenuItem IssueMBtnExit;
    private javax.swing.JLabel LabelID;
    private javax.swing.JRadioButton RBStud;
    private javax.swing.JRadioButton RBTeach;
    private javax.swing.JTextField TxtAOT;
    private javax.swing.JTextField TxtAuthor;
    private javax.swing.JTextField TxtBID;
    private javax.swing.JTextField TxtBName;
    private javax.swing.JTextField TxtBType;
    private javax.swing.JTextField TxtClass;
    private javax.swing.JTextField TxtCopies;
    private javax.swing.JTextField TxtCurl;
    private javax.swing.JTextField TxtFname;
    private javax.swing.JTextField TxtISBN;
    private javax.swing.JTextField TxtLName;
    private javax.swing.JTextField TxtPub;
    private javax.swing.JTextField TxtPurl;
    private javax.swing.JTextField TxtSec;
    private javax.swing.JLabel cimg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JLabel lcls;
    private javax.swing.JLabel lsec;
    private javax.swing.JLabel pimg;
    // End of variables declaration//GEN-END:variables
}
