
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vineet
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLPLogin = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PTPwd = new javax.swing.JPasswordField();
        BtnLogin = new javax.swing.JButton();
        jLPHome = new javax.swing.JLayeredPane();
        HomeBtnAddNew = new javax.swing.JButton();
        HomeBtnRemove = new javax.swing.JButton();
        HomeBtnReturn = new javax.swing.JButton();
        HomeBtnSearch = new javax.swing.JButton();
        HomeBtnIssue = new javax.swing.JButton();
        HomeBtnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LibO");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(672, 650));
        setPreferredSize(new java.awt.Dimension(672, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Header.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLPLogin.setBackground(new java.awt.Color(255, 255, 255));
        jLPLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));
        jLPLogin.setForeground(new java.awt.Color(128, 212, 222));
        jLPLogin.setOpaque(true);
        jLPLogin.setPreferredSize(new java.awt.Dimension(672, 175));

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        BtnLogin.setText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLPLoginLayout = new javax.swing.GroupLayout(jLPLogin);
        jLPLogin.setLayout(jLPLoginLayout);
        jLPLoginLayout.setHorizontalGroup(
            jLPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLPLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLPLoginLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PTPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLPLoginLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(191, 191, 191))
        );
        jLPLoginLayout.setVerticalGroup(
            jLPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPLoginLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jLPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PTPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jLPLogin.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPLogin.setLayer(TxtUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPLogin.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPLogin.setLayer(PTPwd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPLogin.setLayer(BtnLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLPHome.setBackground(new java.awt.Color(255, 255, 255));
        jLPHome.setBorder(javax.swing.BorderFactory.createTitledBorder("Home"));
        jLPHome.setForeground(new java.awt.Color(255, 255, 255));
        jLPHome.setOpaque(true);

        HomeBtnAddNew.setBackground(new java.awt.Color(255, 255, 255));
        HomeBtnAddNew.setFont(new java.awt.Font("Segoe UI Light", 0, 42)); // NOI18N
        HomeBtnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addnew.png"))); // NOI18N
        HomeBtnAddNew.setText("Add New");
        HomeBtnAddNew.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        HomeBtnAddNew.setBorderPainted(false);
        HomeBtnAddNew.setContentAreaFilled(false);
        HomeBtnAddNew.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HomeBtnAddNew.setOpaque(true);
        HomeBtnAddNew.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addnewro.png"))); // NOI18N
        HomeBtnAddNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        HomeBtnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnAddNewActionPerformed(evt);
            }
        });

        HomeBtnRemove.setBackground(new java.awt.Color(255, 255, 255));
        HomeBtnRemove.setFont(new java.awt.Font("Segoe UI Light", 0, 42)); // NOI18N
        HomeBtnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove.png"))); // NOI18N
        HomeBtnRemove.setText("Remove");
        HomeBtnRemove.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        HomeBtnRemove.setBorderPainted(false);
        HomeBtnRemove.setContentAreaFilled(false);
        HomeBtnRemove.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HomeBtnRemove.setOpaque(true);
        HomeBtnRemove.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/removero.png"))); // NOI18N
        HomeBtnRemove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        HomeBtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnRemoveActionPerformed(evt);
            }
        });

        HomeBtnReturn.setBackground(new java.awt.Color(255, 255, 255));
        HomeBtnReturn.setFont(new java.awt.Font("Segoe UI Light", 0, 42)); // NOI18N
        HomeBtnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/return.png"))); // NOI18N
        HomeBtnReturn.setText("Return  ");
        HomeBtnReturn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        HomeBtnReturn.setBorderPainted(false);
        HomeBtnReturn.setContentAreaFilled(false);
        HomeBtnReturn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HomeBtnReturn.setOpaque(true);
        HomeBtnReturn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/returnro.png"))); // NOI18N
        HomeBtnReturn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        HomeBtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnReturnActionPerformed(evt);
            }
        });

        HomeBtnSearch.setBackground(new java.awt.Color(255, 255, 255));
        HomeBtnSearch.setFont(new java.awt.Font("Segoe UI Light", 0, 42)); // NOI18N
        HomeBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search.png"))); // NOI18N
        HomeBtnSearch.setText("Search   ");
        HomeBtnSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        HomeBtnSearch.setBorderPainted(false);
        HomeBtnSearch.setContentAreaFilled(false);
        HomeBtnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HomeBtnSearch.setOpaque(true);
        HomeBtnSearch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Searchro.png"))); // NOI18N
        HomeBtnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        HomeBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnSearchActionPerformed(evt);
            }
        });

        HomeBtnIssue.setBackground(new java.awt.Color(255, 255, 255));
        HomeBtnIssue.setFont(new java.awt.Font("Segoe UI Light", 0, 42)); // NOI18N
        HomeBtnIssue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/issue.png"))); // NOI18N
        HomeBtnIssue.setText("Issue       ");
        HomeBtnIssue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        HomeBtnIssue.setBorderPainted(false);
        HomeBtnIssue.setContentAreaFilled(false);
        HomeBtnIssue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HomeBtnIssue.setOpaque(true);
        HomeBtnIssue.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/issuero.png"))); // NOI18N
        HomeBtnIssue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        HomeBtnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnIssueActionPerformed(evt);
            }
        });

        HomeBtnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        HomeBtnUpdate.setFont(new java.awt.Font("Segoe UI Light", 0, 42)); // NOI18N
        HomeBtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        HomeBtnUpdate.setText("Update");
        HomeBtnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        HomeBtnUpdate.setBorderPainted(false);
        HomeBtnUpdate.setContentAreaFilled(false);
        HomeBtnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        HomeBtnUpdate.setOpaque(true);
        HomeBtnUpdate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/updatero.png"))); // NOI18N
        HomeBtnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        HomeBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLPHomeLayout = new javax.swing.GroupLayout(jLPHome);
        jLPHome.setLayout(jLPHomeLayout);
        jLPHomeLayout.setHorizontalGroup(
            jLPHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPHomeLayout.createSequentialGroup()
                .addComponent(HomeBtnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeBtnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLPHomeLayout.createSequentialGroup()
                .addComponent(HomeBtnIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeBtnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLPHomeLayout.createSequentialGroup()
                .addComponent(HomeBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeBtnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLPHomeLayout.setVerticalGroup(
            jLPHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPHomeLayout.createSequentialGroup()
                .addGroup(jLPHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLPHomeLayout.createSequentialGroup()
                        .addComponent(HomeBtnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomeBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLPHomeLayout.createSequentialGroup()
                        .addComponent(HomeBtnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HomeBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomeBtnIssue, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(HomeBtnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLPHome.setLayer(HomeBtnAddNew, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPHome.setLayer(HomeBtnRemove, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPHome.setLayer(HomeBtnReturn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPHome.setLayer(HomeBtnSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPHome.setLayer(HomeBtnIssue, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPHome.setLayer(HomeBtnUpdate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLPHome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
getContentPane().setBackground(new java.awt.Color(255,255,255));
jLPHome.setVisible(false);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnAddNewActionPerformed
        new insert().setVisible(true);
    }//GEN-LAST:event_HomeBtnAddNewActionPerformed

    private void HomeBtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnRemoveActionPerformed
        new remove().setVisible(true);
    }//GEN-LAST:event_HomeBtnRemoveActionPerformed

    private void HomeBtnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnIssueActionPerformed
        new issue().setVisible(true);
    }//GEN-LAST:event_HomeBtnIssueActionPerformed

    private void HomeBtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnReturnActionPerformed
        new Book_Return().setVisible(true);
    }//GEN-LAST:event_HomeBtnReturnActionPerformed

    private void HomeBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnSearchActionPerformed
        new search().setVisible(true);
    }//GEN-LAST:event_HomeBtnSearchActionPerformed

    private void HomeBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnUpdateActionPerformed
        new update().setVisible(true);
    }//GEN-LAST:event_HomeBtnUpdateActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        String uname = null,pwd = null;
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library", "root", "");
            Statement stmt = (Statement) con.createStatement();
            String q="Select * from auth;";
            ResultSet rs=stmt.executeQuery(q);
            while(rs.next()){
                uname=rs.getString("username");
                pwd=rs.getString("password");
            }
            boolean u,p;
            p=pwd.equals(PTPwd.getText());
            u=uname.equals(TxtUsername.getText());
            if(u&&p){
                jLPHome.setVisible(true);
                jLPLogin.setVisible(false);
                getContentPane().setPreferredSize(new java.awt.Dimension(672, 175));
            }
            else{
                JOptionPane.showMessageDialog(this, "Enter a valid username and password!!", null, 0);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e, null, 0);
        }
    }//GEN-LAST:event_BtnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton HomeBtnAddNew;
    private javax.swing.JButton HomeBtnIssue;
    private javax.swing.JButton HomeBtnRemove;
    private javax.swing.JButton HomeBtnReturn;
    private javax.swing.JButton HomeBtnSearch;
    private javax.swing.JButton HomeBtnUpdate;
    private javax.swing.JPasswordField PTPwd;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JLayeredPane jLPHome;
    private javax.swing.JLayeredPane jLPLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
