import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vineet
 */
public class issue extends javax.swing.JFrame {

    /**
     * Creates new form issue
     */
    public issue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar4 = new javax.swing.JToolBar();
        BtnHome3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtAuthor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtISBN = new javax.swing.JTextField();
        TxtBID = new javax.swing.JTextField();
        TxtBName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtPublisher = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtCopies = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cimg = new javax.swing.JLabel();
        TxtBType = new javax.swing.JTextField();
        BtnBDGo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        RBtnStud = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        RBtnTeach = new javax.swing.JRadioButton();
        TxtAOT = new javax.swing.JTextField();
        LabelID = new javax.swing.JLabel();
        BtnUDGo = new javax.swing.JButton();
        TxtClass = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lcls = new javax.swing.JLabel();
        TxtFName = new javax.swing.JTextField();
        lsec = new javax.swing.JLabel();
        TxtSec = new javax.swing.JTextField();
        TxtLName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pimg = new javax.swing.JLabel();
        BtnIssue = new javax.swing.JButton();
        TxtPURL = new javax.swing.JTextField();
        TxtCURL = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        IssueMBtnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addnew.png"))); // NOI18N
        jLabel2.setText("Enter Book Details");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jToolBar4.setRollover(true);

        BtnHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        BtnHome3.setFocusable(false);
        BtnHome3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnHome3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/homero.png"))); // NOI18N
        BtnHome3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHome3ActionPerformed(evt);
            }
        });
        jToolBar4.add(BtnHome3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/issuethumb.png"))); // NOI18N
        jLabel3.setText("Book Issue Menu");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Book Details"));

        jLabel5.setText("Type:");

        jLabel1.setText("Enter Book ID:");

        jLabel6.setText("Author Name:");

        TxtAuthor.setEditable(false);
        TxtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAuthorActionPerformed(evt);
            }
        });

        jLabel4.setText("ISBN:");

        TxtISBN.setEditable(false);
        TxtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtISBNActionPerformed(evt);
            }
        });

        TxtBName.setEditable(false);
        TxtBName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBNameActionPerformed(evt);
            }
        });

        jLabel7.setText("Book Name:");

        TxtPublisher.setEditable(false);
        TxtPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPublisherActionPerformed(evt);
            }
        });

        jLabel8.setText("Publisher:");

        TxtCopies.setEditable(false);
        TxtCopies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCopiesActionPerformed(evt);
            }
        });

        jLabel9.setText("Copies Avail:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cover Photo"));
        jPanel2.setPreferredSize(new java.awt.Dimension(292, 258));

        cimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(cimg, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TxtBType.setEditable(false);
        TxtBType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBTypeActionPerformed(evt);
            }
        });

        BtnBDGo.setText("Go");
        BtnBDGo.setEnabled(false);
        BtnBDGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBDGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtBType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtBName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtCopies, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(270, 270, 270))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TxtBID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBDGo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(444, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBDGo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(TxtBType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCopies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel1)
                    .addContainerGap(360, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("User Details"));
        jPanel3.setEnabled(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("User Status"));

        buttonGroup1.add(RBtnStud);
        RBtnStud.setSelected(true);
        RBtnStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnStudActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/student.png"))); // NOI18N
        jLabel11.setText("Student");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teacher.png"))); // NOI18N
        jLabel12.setText("Teacher");

        buttonGroup1.add(RBtnTeach);
        RBtnTeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnTeachActionPerformed(evt);
            }
        });

        TxtAOT.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtAOTCaretUpdate(evt);
            }
        });
        TxtAOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAOTActionPerformed(evt);
            }
        });

        LabelID.setText("Enter Admission No:");

        BtnUDGo.setText("Go");
        BtnUDGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUDGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(RBtnStud)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RBtnTeach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(LabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtAOT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnUDGo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RBtnStud)
                    .addComponent(RBtnTeach)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelID)
                    .addComponent(TxtAOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUDGo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TxtClass.setEnabled(false);

        jLabel14.setText("First Name : ");

        lcls.setText("Class : ");

        TxtFName.setEnabled(false);
        TxtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFNameActionPerformed(evt);
            }
        });

        lsec.setText("Section : ");

        TxtSec.setEnabled(false);
        TxtSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSecActionPerformed(evt);
            }
        });

        TxtLName.setEnabled(false);

        jLabel17.setText("Last Name : ");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Photograph"));

        pimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(pimg, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(pimg, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lcls)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TxtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lsec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtSec))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TxtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lcls)
                        .addComponent(lsec))
                    .addComponent(TxtSec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        BtnIssue.setMnemonic('I');
        BtnIssue.setText("Issue");
        BtnIssue.setToolTipText("");
        BtnIssue.setEnabled(false);
        BtnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIssueActionPerformed(evt);
            }
        });
        BtnIssue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnIssueKeyPressed(evt);
            }
        });

        TxtPURL.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtPURLCaretUpdate(evt);
            }
        });
        TxtPURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPURLActionPerformed(evt);
            }
        });

        TxtCURL.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtCURLCaretUpdate(evt);
            }
        });
        TxtCURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCURLActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        IssueMBtnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        IssueMBtnExit.setText("Exit");
        IssueMBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueMBtnExitActionPerformed(evt);
            }
        });
        jMenu1.add(IssueMBtnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Status");

        jMenuItem1.setText("Total Books");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Currently Available");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Total Fine Earned");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel3)
                        .addGap(0, 196, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225)
                .addComponent(TxtPURL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(616, Short.MAX_VALUE)
                    .addComponent(TxtCURL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(88, 88, 88)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnIssue)
                    .addComponent(TxtPURL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(662, Short.MAX_VALUE)
                    .addComponent(TxtCURL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IssueMBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueMBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_IssueMBtnExitActionPerformed

    private void BtnHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHome3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnHome3ActionPerformed

    private void TxtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAuthorActionPerformed

    private void TxtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtISBNActionPerformed

    private void TxtBNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBNameActionPerformed

    private void TxtPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPublisherActionPerformed

    private void TxtCopiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCopiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCopiesActionPerformed

    private void RBtnStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnStudActionPerformed
        LabelID.setText("Enter Admission No:");
        lcls.setVisible(true);
        TxtClass.setVisible(true);
        lsec.setVisible(true);
        TxtSec.setVisible(true);
        TxtFName.setText("");
        TxtLName.setText("");
        TxtClass.setText("");
        TxtSec.setText("");
        TxtPURL.setText("");
        
    }//GEN-LAST:event_RBtnStudActionPerformed

    private void RBtnTeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnTeachActionPerformed
        LabelID.setText("Enter Teacher ID");
        lcls.setVisible(false);
        TxtClass.setVisible(false);
        lsec.setVisible(false);
        TxtSec.setVisible(false);
        TxtFName.setText("");
        TxtLName.setText("");
        TxtClass.setText("");
        TxtSec.setText("");
        TxtPURL.setText("");
    }//GEN-LAST:event_RBtnTeachActionPerformed

    private void TxtSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSecActionPerformed

    }//GEN-LAST:event_TxtSecActionPerformed

    private void TxtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFNameActionPerformed

    private void TxtBTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBTypeActionPerformed

    private void TxtAOTCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtAOTCaretUpdate
        
    }//GEN-LAST:event_TxtAOTCaretUpdate

    private void TxtAOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAOTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAOTActionPerformed

    private void BtnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIssueActionPerformed
        if(Integer.parseInt(TxtCopies.getText())>0){
        if (RBtnStud.isSelected()==true)
        {
            String uid, BID;
            BID = TxtBID.getText();
            uid = TxtAOT.getText();
            try
            {
                Class.forName("java.sql.DriverManager");
                com.mysql.jdbc.Connection con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library", "root", "");
                com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                String query= "INSERT INTO Issue VALUES('"+BID+"','s','"+uid+"',CURDATE());";
                String upd="UPDATE Books set Copies_Available=Copies_available-1 WHERE Book_ID='"+TxtBID.getText()+"';";
                System.out.println(query);
                System.out.println(upd);
                stmt.executeUpdate(query);
                stmt.executeUpdate(upd);
                JOptionPane.showMessageDialog(this,"Book Issued Successfully!!!");
                this.setVisible(false);
                new Home().setVisible(true);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }if (RBtnTeach.isSelected()==true)
        {
            String uid, BID;
            BID = TxtBID.getText();
            uid = TxtAOT.getText();
            try
            {
                Class.forName("java.sql.DriverManager");
                com.mysql.jdbc.Connection con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library", "root", "");
                com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement();
                String query= "INSERT INTO Issue VALUES('"+BID+"','t','"+uid+"',CURDATE());";
                String upd="UPDATE Books set Copies_Available=Copies_available-1 WHERE Book_ID='"+TxtBID.getText()+"';";
                System.out.println(query);
                System.out.println(upd);
                stmt.executeUpdate(query);                
                stmt.executeUpdate(upd);
                JOptionPane.showMessageDialog(this,"Book Issued Successfully!!!");
                this.dispose();
                new issue().setVisible(true);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        }
        else
            JOptionPane.showMessageDialog(this, "Book already issued!", null, 0);
        
        
    }//GEN-LAST:event_BtnIssueActionPerformed

    private void TxtPURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPURLActionPerformed

    private void TxtPURLCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtPURLCaretUpdate
        Image img = Toolkit.getDefaultToolkit().createImage("E:\\TEMP\\"+TxtPURL.getText()+".JPG").getScaledInstance(192, 235, 0);
        ImageIcon ic = new ImageIcon(img);
        pimg.setIcon(ic);
    }//GEN-LAST:event_TxtPURLCaretUpdate

    private void BtnUDGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUDGoActionPerformed
        if (RBtnStud.isSelected()==true)
        {
            if (TxtAOT.getText().equals("") == false) {
                try {
                    Class.forName("java.sql.Driver");
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library", "root", "");
                    Statement stmt = (Statement) con.createStatement();
                    String q1 = "SELECT * FROM Student WHERE admno='" + TxtAOT.getText() + "';";
                    System.out.println(q1);
                    ResultSet rs = stmt.executeQuery(q1);
                    while (rs.next())
                    {
                        TxtFName.setText(rs.getString("first_name"));
                        TxtLName.setText(rs.getString("last_name"));
                        TxtClass.setText(rs.getString("class"));
                        TxtSec.setText(rs.getString("section"));
                        TxtPURL.setText(rs.getString("purl"));
                    }
                    BtnBDGo.setEnabled(true);
                    if (TxtFName.getText().equals("")){
                        JOptionPane.showMessageDialog(this, "No Student Record Found");
                        TxtAOT.setText("");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Admission No !!!");
            }
        }
        else if (RBtnTeach.isSelected()==true)
        {
            if (TxtAOT.getText().equals("") == false) {
                try {
                    Class.forName("java.sql.Driver");
                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library", "root", "");
                    Statement stmt = (Statement) con.createStatement();
                    String q1 = "SELECT * FROM teacher WHERE tid='" + TxtAOT.getText() + "';";
                    System.out.println(q1);
                    ResultSet rs = stmt.executeQuery(q1);
                    while (rs.next())
                    {
                        TxtFName.setText(rs.getString("First_name"));
                        TxtLName.setText(rs.getString("last_name"));
                        TxtPURL.setText(rs.getString("purl"));                     
                    }
                    BtnBDGo.setEnabled(true);
                    if (TxtFName.getText().equals("")){
                        JOptionPane.showMessageDialog(this, "No Teacher Record Found");
                        TxtAOT.setText("");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Teacher ID !!!");
            }
        }
    }//GEN-LAST:event_BtnUDGoActionPerformed

    private void BtnBDGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBDGoActionPerformed
        if (TxtBID.getText().equals("")==false)
        {
            try
            {
                Class.forName("java.sql.Driver");
                com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library","root","");
                com.mysql.jdbc.Statement stmt=(com.mysql.jdbc.Statement) con.createStatement();
                String q1="SELECT * FROM Books WHERE Book_ID='"+TxtBID.getText()+"';";
                System.out.println(q1);
                ResultSet rs=stmt.executeQuery(q1);
                while(rs.next())
                {
                    TxtISBN.setText(rs.getString("ISBN"));
                    TxtBName.setText(rs.getString("Book_Name"));
                    TxtBType.setText(rs.getString("Book_Type"));
                    TxtAuthor.setText(rs.getString("Author"));
                    TxtPublisher.setText(rs.getString("Publisher"));
                    TxtCopies.setText(rs.getString("Copies_Available"));
                    TxtCURL.setText(rs.getString("CURL"));
                }
                BtnIssue.setEnabled(true);
                
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        else JOptionPane.showMessageDialog(this, "Invalid Book ID !!!");
    }//GEN-LAST:event_BtnBDGoActionPerformed

    private void TxtCURLCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtCURLCaretUpdate
        Image img = Toolkit.getDefaultToolkit().createImage("E:\\temp\\"+TxtCURL.getText()+".jpg").getScaledInstance(192, 235, 0);
        ImageIcon ic = new ImageIcon(img);
        cimg.setIcon(ic);
    }//GEN-LAST:event_TxtCURLCaretUpdate

    private void TxtCURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCURLActionPerformed

    private void BtnIssueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnIssueKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIssueKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new issue().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBDGo;
    private javax.swing.JButton BtnHome3;
    private javax.swing.JButton BtnIssue;
    private javax.swing.JButton BtnUDGo;
    private javax.swing.JMenuItem IssueMBtnExit;
    private javax.swing.JLabel LabelID;
    private javax.swing.JRadioButton RBtnStud;
    private javax.swing.JRadioButton RBtnTeach;
    private javax.swing.JTextField TxtAOT;
    private javax.swing.JTextField TxtAuthor;
    private javax.swing.JTextField TxtBID;
    private javax.swing.JTextField TxtBName;
    private javax.swing.JTextField TxtBType;
    private javax.swing.JTextField TxtCURL;
    private javax.swing.JTextField TxtClass;
    private javax.swing.JTextField TxtCopies;
    private javax.swing.JTextField TxtFName;
    private javax.swing.JTextField TxtISBN;
    private javax.swing.JTextField TxtLName;
    private javax.swing.JTextField TxtPURL;
    private javax.swing.JTextField TxtPublisher;
    private javax.swing.JTextField TxtSec;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cimg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JLabel lcls;
    private javax.swing.JLabel lsec;
    private javax.swing.JLabel pimg;
    // End of variables declaration//GEN-END:variables
}
