import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vineet
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
        scb2.setVisible(false);
        scb3.setVisible(false);
        scb4.setVisible(false);
        stxt2.setVisible(false);
        stxt3.setVisible(false);
        stxt4.setVisible(false);
        spbtn2.setVisible(false);
        spbtn3.setVisible(false);        
        sl2.setVisible(false);
        sl3.setVisible(false);
        sl4.setVisible(false);
        sdbtn2.setVisible(false);
        sdbtn3.setVisible(false);
        sdbtn4.setVisible(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        BtnHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        scb1 = new javax.swing.JComboBox();
        sl1 = new javax.swing.JLabel();
        stxt1 = new javax.swing.JTextField();
        spbtn1 = new javax.swing.JButton();
        spbtn2 = new javax.swing.JButton();
        stxt2 = new javax.swing.JTextField();
        sl2 = new javax.swing.JLabel();
        scb2 = new javax.swing.JComboBox();
        spbtn3 = new javax.swing.JButton();
        stxt3 = new javax.swing.JTextField();
        sl3 = new javax.swing.JLabel();
        scb3 = new javax.swing.JComboBox();
        stxt4 = new javax.swing.JTextField();
        sl4 = new javax.swing.JLabel();
        scb4 = new javax.swing.JComboBox();
        sdbtn2 = new javax.swing.JButton();
        sdbtn3 = new javax.swing.JButton();
        sdbtn4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        RBYes = new javax.swing.JRadioButton();
        RBNo = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSearch = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RemoveMBtnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        BtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        BtnHome.setFocusable(false);
        BtnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/homero.png"))); // NOI18N
        BtnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnHome);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search.png"))); // NOI18N
        jLabel2.setText("Search Details");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Where"));

        scb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Book_ID", "ISBN", "Book_Name", "Author", "Publisher", "Copies" }));

        sl1.setText(":");

        stxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stxt1ActionPerformed(evt);
            }
        });

        spbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        spbtn1.setBorder(null);
        spbtn1.setBorderPainted(false);
        spbtn1.setContentAreaFilled(false);
        spbtn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plusro.png"))); // NOI18N
        spbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spbtn1ActionPerformed(evt);
            }
        });

        spbtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        spbtn2.setBorder(null);
        spbtn2.setBorderPainted(false);
        spbtn2.setContentAreaFilled(false);
        spbtn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plusro.png"))); // NOI18N
        spbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spbtn2ActionPerformed(evt);
            }
        });

        sl2.setText(":");

        scb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Book_ID", "ISBN", "Book_Name", "Author", "Publisher", "Copies" }));

        spbtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        spbtn3.setBorder(null);
        spbtn3.setBorderPainted(false);
        spbtn3.setContentAreaFilled(false);
        spbtn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plusro.png"))); // NOI18N
        spbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spbtn3ActionPerformed(evt);
            }
        });

        sl3.setText(":");

        scb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Book_ID", "ISBN", "Book_Name", "Author", "Publisher", "Copies" }));
        scb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scb3ActionPerformed(evt);
            }
        });

        sl4.setText(":");

        scb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Book_ID", "ISBN", "Book_Name", "Author", "Publisher", "Copies" }));

        sdbtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del.png"))); // NOI18N
        sdbtn2.setBorder(null);
        sdbtn2.setBorderPainted(false);
        sdbtn2.setContentAreaFilled(false);
        sdbtn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delro.png"))); // NOI18N
        sdbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdbtn2ActionPerformed(evt);
            }
        });

        sdbtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del.png"))); // NOI18N
        sdbtn3.setBorder(null);
        sdbtn3.setBorderPainted(false);
        sdbtn3.setContentAreaFilled(false);
        sdbtn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delro.png"))); // NOI18N
        sdbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdbtn3ActionPerformed(evt);
            }
        });

        sdbtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del.png"))); // NOI18N
        sdbtn4.setBorder(null);
        sdbtn4.setBorderPainted(false);
        sdbtn4.setContentAreaFilled(false);
        sdbtn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delro.png"))); // NOI18N
        sdbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdbtn4ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Searchthumb.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Issued"));

        buttonGroup1.add(RBYes);
        RBYes.setSelected(true);
        RBYes.setText("Yes");

        buttonGroup1.add(RBNo);
        RBNo.setText("No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(RBYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBNo)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBYes)
                    .addComponent(RBNo))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(scb1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sl1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(scb2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sl2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sdbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(scb4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sl4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sdbtn4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(scb3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sl3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sdbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sl1)
                        .addComponent(stxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sl2)
                        .addComponent(stxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(scb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sl3)
                                .addComponent(stxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sdbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(scb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sl4)
                                .addComponent(stxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(sdbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TableSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "ISBN", "Book Name", "Author", "Publisher", "Copies", "Issued by", "Copies available"
            }
        ));
        TableSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSearch);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        RemoveMBtnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        RemoveMBtnExit.setText("Exit");
        RemoveMBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveMBtnExitActionPerformed(evt);
            }
        });
        jMenu1.add(RemoveMBtnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Status");

        jMenuItem1.setText("Total Books");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Currently Available");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Total Fine Earned");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveMBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveMBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_RemoveMBtnExitActionPerformed

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void sdbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdbtn2ActionPerformed
        scb2.setVisible(false);
        stxt2.setVisible(false);
        spbtn2.setVisible(false);     
        sl2.setVisible(false);
        sdbtn2.setVisible(false);
        spbtn1.setVisible(true); 
    }//GEN-LAST:event_sdbtn2ActionPerformed

    private void sdbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdbtn3ActionPerformed
        scb3.setVisible(false);
        stxt3.setVisible(false);
        spbtn3.setVisible(false);     
        sl3.setVisible(false);
        sdbtn3.setVisible(false);        
        sdbtn2.setVisible(true); 
        spbtn2.setVisible(true); 
    }//GEN-LAST:event_sdbtn3ActionPerformed

    private void sdbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdbtn4ActionPerformed
        scb4.setVisible(false);
        stxt4.setVisible(false);
        sl4.setVisible(false);
        sdbtn4.setVisible(false);        
        spbtn3.setVisible(true);        
        sdbtn3.setVisible(true);
    }//GEN-LAST:event_sdbtn4ActionPerformed

    private void spbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spbtn1ActionPerformed
        scb2.setVisible(true);
        stxt2.setVisible(true);
        spbtn2.setVisible(true);     
        sl2.setVisible(true);
        sdbtn2.setVisible(true);
        spbtn1.setVisible(false);        
    }//GEN-LAST:event_spbtn1ActionPerformed

    private void spbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spbtn2ActionPerformed
        scb3.setVisible(true);
        stxt3.setVisible(true);
        spbtn3.setVisible(true);     
        sl3.setVisible(true);
        sdbtn3.setVisible(true);
        spbtn2.setVisible(false);
        sdbtn2.setVisible(false);
    }//GEN-LAST:event_spbtn2ActionPerformed

    private void spbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spbtn3ActionPerformed
        scb4.setVisible(true);
        stxt4.setVisible(true);    
        sl4.setVisible(true);
        sdbtn4.setVisible(true);
        spbtn3.setVisible(false);
        sdbtn3.setVisible(false);
    }//GEN-LAST:event_spbtn3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel tm = (DefaultTableModel) TableSearch.getModel();
       //for(int i=0;i<=tm.getRowCount();i++)
       //tm.removeRow(i);
       tm.setRowCount(0);
        String query = null;
                try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/lIBRARY", "root", "");
            Statement stmt = (Statement) con.createStatement();
            ResultSet rs = null;
            if(RBYes.isSelected()){
                if (scb1.isVisible()==true)
                query = "Select Books.Book_ID, ISBN, Book_Name, Author, Publisher, Copies, uid, Copies_available  from books,issue where books.book_id= issue.book_id and books."+scb1.getSelectedItem()+"='"+stxt1.getText()+"';";
                if (scb2.isVisible()==true)
                query = "Select books.Book_ID, isbn, Book_name, author, publisher, copies, uid, copies_available  from books,issue where books.bid= issue.bid and books."+scb1.getSelectedItem()+"='"+stxt1.getText()+"' and "+scb2.getSelectedItem()+"='"+stxt2.getText()+"';";
                if (scb3.isVisible()==true && scb2.isVisible()==true)
                query = "Select books.Book_ID, isbn, Book_name, author, publisher, copies, uid, copies_available  from books,issue where books.bid= issue.bid and books."+scb1.getSelectedItem()+"='"+stxt1.getText()+"' and "+scb2.getSelectedItem()+"='"+stxt2.getText()+"' and "+scb3.getSelectedItem()+"='"+stxt3.getText()+"';";
                if (scb4.isVisible()==true && scb3.isVisible()==true && scb2.isVisible()==true)
                query = "Select books.Book_ID, isbn, Book_name, author, publisher, copies, uid, copies_available  from books,issue where books.bid= issue.bid and books."+scb1.getSelectedItem()+"='"+stxt1.getText()+"' and "+scb2.getSelectedItem()+"='"+stxt2.getText()+"' and "+scb3.getSelectedItem()+"='"+stxt3.getText()+"' and "+scb4.getSelectedItem()+"='"+stxt4.getText()+"';";
                System.out.println(query);
                rs = stmt.executeQuery(query);            
                while (rs.next()) {
                    tm.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5), rs.getInt(6), rs.getString(7), rs.getInt(8)});
                }   
            }
            else if(RBNo.isSelected()){
                if (scb1.isVisible()==true)
                query = "Select Book_ID, ISBN, Book_Name, Author, Publisher, Copies, Copies_available  from books where books."+scb1.getSelectedItem()+"='"+stxt1.getText()+"';";
                if (scb2.isVisible()==true)
                query = "Select Book_ID, ISBN, Book_Name, Author, Publisher, Copies, Copies_available  from books where books."+scb1.getSelectedItem()+"='"+stxt1.getText()+"' and "+scb2.getSelectedItem()+"='"+stxt2.getText()+"';";
                if (scb3.isVisible()==true && scb2.isVisible()==true)
                query = "Select Book_ID, ISBN, Book_Name, Author, Publisher, Copies, Copies_available  from books where books."+scb1.getSelectedItem()+"='"+stxt1.getText()+"' and "+scb2.getSelectedItem()+"='"+stxt2.getText()+"' and "+scb3.getSelectedItem()+"='"+stxt3.getText()+"';";
                if (scb4.isVisible()==true && scb3.isVisible()==true && scb2.isVisible()==true)
                query = "Select Book_ID, ISBN, Book_Name, Author, Publisher, Copies, Copies_available  from books where books."+scb1.getSelectedItem()+"='"+stxt1.getText()+"' and "+scb2.getSelectedItem()+"='"+stxt2.getText()+"' and "+scb3.getSelectedItem()+"='"+stxt3.getText()+"' and "+scb4.getSelectedItem()+"='"+stxt4.getText()+"';";
                System.out.println(query);
                rs = stmt.executeQuery(query);            
                while (rs.next()) {
                    if(rs.getInt(7)>0)
                    tm.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5), rs.getInt(6), "No One", rs.getInt(7)});
                }            
            }
            rs.close();
            stmt.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TableSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSearchMouseClicked
       
    }//GEN-LAST:event_TableSearchMouseClicked

    private void stxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stxt1ActionPerformed

    private void scb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHome;
    private javax.swing.JRadioButton RBNo;
    private javax.swing.JRadioButton RBYes;
    private javax.swing.JMenuItem RemoveMBtnExit;
    private javax.swing.JTable TableSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox scb1;
    private javax.swing.JComboBox scb2;
    private javax.swing.JComboBox scb3;
    private javax.swing.JComboBox scb4;
    private javax.swing.JButton sdbtn2;
    private javax.swing.JButton sdbtn3;
    private javax.swing.JButton sdbtn4;
    private javax.swing.JLabel sl1;
    private javax.swing.JLabel sl2;
    private javax.swing.JLabel sl3;
    private javax.swing.JLabel sl4;
    private javax.swing.JButton spbtn1;
    private javax.swing.JButton spbtn2;
    private javax.swing.JButton spbtn3;
    private javax.swing.JTextField stxt1;
    private javax.swing.JTextField stxt2;
    private javax.swing.JTextField stxt3;
    private javax.swing.JTextField stxt4;
    // End of variables declaration//GEN-END:variables
}
