import java.awt.Image;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.*; 
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import com.mysql.jdbc.Statement;
import com.mysql.jdbc.Connection;
import java.io.File;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vineet
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    public update() {
        initComponents();
        cFileFilter filter  = new cFileFilter();
        jfc.addChoosableFileFilter(filter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameFC = new javax.swing.JFrame();
        jfc = new javax.swing.JFileChooser();
        jToolBar4 = new javax.swing.JToolBar();
        BtnHome3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtAuthor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtISBN = new javax.swing.JTextField();
        TxtBID = new javax.swing.JTextField();
        TxtBName = new javax.swing.JTextField();
        TxtBType = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TxtPublisher = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtCopies = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cimg = new javax.swing.JLabel();
        TxtCURL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BtnGo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        NewMBtnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        FrameFC.setMinimumSize(new java.awt.Dimension(602, 361));
        FrameFC.setResizable(false);

        jfc.setAcceptAllFileFilterUsed(false);
        jfc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jfc.setMaximumSize(new java.awt.Dimension(582, 297));
        jfc.setMinimumSize(new java.awt.Dimension(582, 297));
        jfc.setPreferredSize(new java.awt.Dimension(582, 297));
        jfc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jfcMouseEntered(evt);
            }
        });
        jfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameFCLayout = new javax.swing.GroupLayout(FrameFC.getContentPane());
        FrameFC.getContentPane().setLayout(FrameFCLayout);
        FrameFCLayout.setHorizontalGroup(
            FrameFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameFCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jfc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FrameFCLayout.setVerticalGroup(
            FrameFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameFCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jfc, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar4.setRollover(true);

        BtnHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        BtnHome3.setFocusable(false);
        BtnHome3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnHome3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/homero.png"))); // NOI18N
        BtnHome3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHome3ActionPerformed(evt);
            }
        });
        jToolBar4.add(BtnHome3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        jLabel2.setText("Update Book Details");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setText("Type:");

        jLabel1.setText("Enter Book ID:");

        jLabel6.setText("Author Name:");

        TxtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAuthorActionPerformed(evt);
            }
        });

        jLabel3.setText("ISBN:");

        TxtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtISBNActionPerformed(evt);
            }
        });

        TxtBID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBIDActionPerformed(evt);
            }
        });

        TxtBName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBNameActionPerformed(evt);
            }
        });

        TxtBType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Other", "Course Book", "Encyclopedia", "Magazine", "Novel", "Poetry", "Reference Book" }));

        jLabel4.setText("Book Name:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        TxtPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPublisherActionPerformed(evt);
            }
        });

        jLabel7.setText("Publisher:");

        TxtCopies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCopiesActionPerformed(evt);
            }
        });

        jLabel8.setText("Copies:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cover Photo"));

        cimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cimg, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cimg, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        TxtCURL.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtCURLCaretUpdate(evt);
            }
        });
        TxtCURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCURLActionPerformed(evt);
            }
        });

        jLabel9.setText("Cover Photo URL:");

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnGo.setText("Go");
        BtnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtBName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtCopies, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtBID, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtCURL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtBID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(BtnGo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtBType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCopies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jButton1))))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        NewMBtnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        NewMBtnExit.setText("Exit");
        NewMBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewMBtnExitActionPerformed(evt);
            }
        });
        jMenu1.add(NewMBtnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Status");

        jMenuItem1.setText("Total Books");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Currently Available");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Total Fine Earned");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73))))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String bid;
    private void NewMBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewMBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_NewMBtnExitActionPerformed

    private void BtnHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHome3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnHome3ActionPerformed

    private void TxtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAuthorActionPerformed

    private void TxtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtISBNActionPerformed

    private void TxtBNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBNameActionPerformed

    private void TxtPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPublisherActionPerformed

    private void TxtCopiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCopiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCopiesActionPerformed

    private void TxtCURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCURLActionPerformed

    private void TxtBIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBIDActionPerformed

    private void BtnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGoActionPerformed
        if (TxtBID.getText().equals("") == false) {
            TxtISBN.setText("");
            TxtBName.setText("");
            TxtAuthor.setText("");
            TxtPublisher.setText("");
            TxtCopies.setText("");
            TxtCURL.setText("");
            try {
                Class.forName("java.sql.Driver");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library", "root", "");
                Statement stmt = (Statement) con.createStatement();
                String q1 = "SELECT * FROM Books WHERE Book_ID='" + TxtBID.getText() + "';";
                System.out.println(q1);
                ResultSet rs = stmt.executeQuery(q1);
                while (rs.next()) {
                    bid=rs.getString("Book_ID");
                    TxtISBN.setText(rs.getString("ISBN"));
                    TxtBName.setText(rs.getString("Book_Name"));
                    TxtBType.setSelectedItem(rs.getString("Book_Type"));
                    TxtAuthor.setText(rs.getString("Author"));
                    TxtPublisher.setText(rs.getString("Publisher"));
                    TxtCopies.setText(rs.getString("Copies"));
                    String CURL = rs.getString("CURL");
                    TxtCURL.setText(CURL);
                }                
                if (TxtISBN.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Book with Book_ID["+TxtBID.getText()+"] does not exists! Enter a valid Book ID");
                    TxtBID.setText("");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Book ID !!!");
        }
    }//GEN-LAST:event_BtnGoActionPerformed

    private void TxtCURLCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtCURLCaretUpdate
        Image img = Toolkit.getDefaultToolkit().createImage("E:\\TEMP\\"+TxtCURL.getText()+".JPG").getScaledInstance(192, 235, 0);
        ImageIcon ic = new ImageIcon(img);
        cimg.setIcon(ic);
    }//GEN-LAST:event_TxtCURLCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrameFC.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jfcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jfcMouseEntered

   }//GEN-LAST:event_jfcMouseEntered

    private void jfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfcActionPerformed
        String ac = evt.getActionCommand();
        if (ac.equals("ApproveSelection")) {
            if (jfc.getSelectedFile().getName().endsWith(".jpg") || jfc.getSelectedFile().getName().endsWith(".gif") || jfc.getSelectedFile().getName().endsWith(".png") || jfc.getSelectedFile().getName().endsWith(".bmp")) {
                Path FROM = Paths.get(jfc.getSelectedFile().getAbsolutePath());
                Path TO = Paths.get("E:\\temp\\"+jfc.getSelectedFile().getName().substring(0, jfc.getSelectedFile().getName().length()-4)+".jpg");
                CopyOption[] options = new CopyOption[]{
                    StandardCopyOption.REPLACE_EXISTING,
                    StandardCopyOption.COPY_ATTRIBUTES
                }; 
                try {
                    Files.copy(FROM, TO, options);
                } catch (IOException ex) {
                    Logger.getLogger(update.class.getName()).log(Level.SEVERE, null, ex);
                }

                TxtCURL.setText(jfc.getSelectedFile().getName().substring(0, jfc.getSelectedFile().getName().length()-4));
                FrameFC.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "You Selected invalid file!!!");
            }
        } else if (ac.equals("CancelSelection")) {
            FrameFC.setVisible(false);
        }
    }//GEN-LAST:event_jfcActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String ISBN, Bname, type, author, pub, copies, cpurl;
        ISBN = TxtISBN.getText();
        Bname = TxtBName.getText();
        type = (String) TxtBType.getSelectedItem();
        author = TxtAuthor.getText();
        pub = TxtPublisher.getText();
        copies = TxtCopies.getText();
        cpurl = TxtCURL.getText();
        int bcopies = Integer.parseInt(copies);
        if (TxtBID.getText().equals("") == false) {
            try {
                Class.forName("java.sql.Driver");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/Library", "root", "");
                Statement stmt = (Statement) con.createStatement();
                String q1 = "UPDATE Books SET Book_ID='"+TxtBID.getText()+"', ISBN='"+ISBN+"', Book_Name='"+Bname+"', Book_Type='"+type+"', Author='"+author+"', Publisher='"+pub+"', copies='"+copies+"', CURL='"+cpurl+"' WHERE Book_ID='" + bid + "';";
                System.out.println(q1);
                stmt.executeUpdate(q1);
                JOptionPane.showMessageDialog(this, "Information Updated Successfully!!!");
                this.dispose();
                new update().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter a valid Book ID First !!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new update().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGo;
    private javax.swing.JButton BtnHome3;
    private javax.swing.JFrame FrameFC;
    private javax.swing.JMenuItem NewMBtnExit;
    private javax.swing.JTextField TxtAuthor;
    private javax.swing.JTextField TxtBID;
    private javax.swing.JTextField TxtBName;
    private javax.swing.JComboBox TxtBType;
    private javax.swing.JTextField TxtCURL;
    private javax.swing.JTextField TxtCopies;
    private javax.swing.JTextField TxtISBN;
    private javax.swing.JTextField TxtPublisher;
    private javax.swing.JLabel cimg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JFileChooser jfc;
    // End of variables declaration//GEN-END:variables
}
